# Generated by Django 5.2.3 on 2025-06-11 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('DMR', 'DMR'), ('M17', 'M17'), ('YSF', 'YSF'), ('DST', 'D-Star'), ('ALL', 'AllStar'), ('ECL', 'Echolink'), ('IRL', 'IRLP')], max_length=3)),
                ('target', models.CharField(max_length=12)),
                ('description', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('public', models.BooleanField(default=True)),
                ('operator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Talkgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgid', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.owner')),
            ],
        ),
    ]
