# Generated by Django 5.2.3 on 2025-06-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_talkgroup_created_at_talkgroup_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='shortname',
            field=models.CharField(default='DVDU', max_length=6),
            preserve_default=False,
        ),
    ]
