# Generated by Django 5.2.3 on 2025-06-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bridge_talkgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='shortname',
            field=models.CharField(max_length=8),
        ),
    ]
