# Generated by Django 5.2.3 on 2025-06-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_owner_shortname'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridge',
            name='network',
            field=models.CharField(blank=True, default=None, max_length=18, null=True),
        ),
    ]
