# Generated by Django 5.2.3 on 2025-06-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_bridge_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_id', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('hostname', models.CharField(blank=True, default=None, max_length=84, null=True)),
                ('hotspot_port', models.IntegerField(blank=True, default=True, null=True)),
                ('hotspot_pwd', models.CharField(blank=True, default=True, max_length=18, null=True)),
                ('listed', models.BooleanField(default=False)),
            ],
        ),
    ]
