# Generated by Django 5.2.3 on 2025-06-11 02:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
