# Generated by Django 5.2.3 on 2025-06-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_server_created_at_server_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='hotspot_allow',
            field=models.BooleanField(default=True),
        ),
    ]
