# Generated by Django 5.2.3 on 2025-06-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_server_hotspot_allow'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='server_name',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
